[workspace]
members = [
    "logos-core",
    "logos-render",
    "logos-text",
    "logos-desktop",
    "logos-wasm",
    "logos-layout"
, "logos-collab"]
resolver = "2"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
