[package]
name = "logos-text"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmic-text = "0.12"
bytemuck = { version = "1.25.0", features = ["derive"] }
log = "0.4"
lru = "0.13"
font-kit = "0.14.3"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "text_benchmark"
harness = false
